pipeline_id: slop-stop-pipeline
item_unit: paragraph
determinism_policy: strict

stages:
  - id: preprocessing
    mode: whole_run
    inputs: []
    outputs:
      - family: preprocessed
        pattern: preprocessed/preprocessed.json
        schema: preprocessed.schema.json
      - family: paragraphs
        pattern: preprocessed/paragraphs.jsonl
        schema: paragraphs.schema.json

  - id: word_frequency_benchmark
    mode: whole_run
    inputs:
      - family: preprocessed
        pattern: preprocessed/preprocessed.json
        schema: preprocessed.schema.json
    outputs:
      - family: lexical_frequency
        pattern: lexical/word_frequency_report.json
        schema: word_frequency_report.schema.json

  - id: style_slop_detectors
    mode: whole_run
    inputs:
      - family: preprocessed
        pattern: preprocessed/preprocessed.json
        schema: preprocessed.schema.json
      - family: lexical_frequency
        pattern: lexical/word_frequency_report.json
        schema: word_frequency_report.schema.json
    outputs:
      - family: style_slop_findings
        pattern: diagnostics/style_slop_findings.json
        schema: style_slop_findings.schema.json
      - family: rewrite_candidates
        pattern: diagnostics/rewrite_candidates.jsonl
        schema: rewrite_candidates.schema.json

  - id: transform
    mode: whole_run
    inputs:
      - family: rewrite_candidates
        pattern: diagnostics/rewrite_candidates.jsonl
        schema: rewrite_candidates.schema.json
    outputs:
      - family: transformed_rewrites
        pattern: transforms/transformed.jsonl
        schema: transformed_rewrites.schema.json

  - id: reviewer_pass
    mode: whole_run
    inputs:
      - family: transformed_rewrites
        pattern: transforms/transformed.jsonl
        schema: transformed_rewrites.schema.json
    outputs:
      - family: reviewed_rewrites
        pattern: review/reviewed.jsonl
        schema: reviewed_rewrites.schema.json
      - family: review_summary
        pattern: review/review_summary.json
        schema: review_summary.schema.json

  - id: publish
    mode: whole_run
    inputs:
      - family: reviewed_rewrites
        pattern: review/reviewed.jsonl
        schema: reviewed_rewrites.schema.json
      - family: review_summary
        pattern: review/review_summary.json
        schema: review_summary.schema.json
    outputs:
      - family: manifest
        pattern: manifest.json
        schema: manifest.schema.json
