pipeline_id: translate-pipeline
item_unit: paragraph
determinism_policy: strict

params:
  targets:
    languages:
      - Arabic
      - Bengali
      - Deutch
      - English
      - French
      - Gujarati
      - Hindi
      - Italian
      - Japanese
      - Korean
      - Mandarin_Chinese
      - Marathi
      - Norwegian
      - Persian
      - Portuguese
      - Russian
      - Spanish
      - Tamil
      - Telugu
      - Turkish
      - Vietnamese
      - Western_Punjabi

stages:
  - id: source_ingest
    mode: whole_run
    inputs: []
    outputs:
      - family: paragraphs
        pattern: paragraphs.jsonl
        schema: paragraphs.schema.json
      - family: manifest
        pattern: manifest.json
        schema: manifest.schema.json

  - id: translate_pass1
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: paragraphs
        pattern: paragraphs.jsonl
        schema: paragraphs.schema.json
    outputs:
      - family: pass1_translations
        pattern: pass1_pre/{lang}/paragraphs.jsonl
        schema: paragraphs.schema.json

  - id: translate_pass2
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: paragraphs
        pattern: paragraphs.jsonl
        schema: paragraphs.schema.json
      - family: pass1_translations
        pattern: pass1_pre/{lang}/paragraphs.jsonl
        schema: paragraphs.schema.json
    outputs:
      - family: pass2_translations
        pattern: pass2_pre/{lang}/paragraphs.jsonl
        schema: paragraphs.schema.json

  - id: qa_review
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: paragraphs
        pattern: paragraphs.jsonl
        schema: paragraphs.schema.json
      - family: pass2_translations
        pattern: pass2_pre/{lang}/paragraphs.jsonl
        schema: paragraphs.schema.json
    outputs:
      - family: qa_reviewed_translations
        pattern: qa_review/{lang}/paragraphs.jsonl
        schema: paragraphs.schema.json

  - id: candidate_assembly
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: qa_reviewed_translations
        pattern: qa_review/{lang}/paragraphs.jsonl
        schema: paragraphs.schema.json
    outputs:
      - family: candidate_manuscripts
        pattern: final/{lang}/candidate.md
      - family: candidate_paragraph_maps
        pattern: final/{lang}/candidate_map.jsonl
        schema: candidate_map.schema.json

  - id: review_grammar
    placeholder: true
    mode: whole_run
    inputs:
      - family: pass2_translations
        pattern: pass2_pre/paragraphs.jsonl
        schema: paragraphs.schema.json
    outputs:
      - family: grammar_reviews
        pattern: review/grammar/review.json
        schema: review.schema.json

  - id: review_typography
    placeholder: true
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: candidate_manuscripts
        pattern: final/{lang}/candidate.md
        schema: candidate.schema.json
    outputs:
      - family: typography_reviews
        pattern: review/{lang}/typography/review.json
        schema: review.schema.json

  - id: review_critics
    placeholder: true
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: candidate_manuscripts
        pattern: final/{lang}/candidate.md
        schema: candidate.schema.json
    outputs:
      - family: critics_reviews
        pattern: review/{lang}/critics/review.json
        schema: review.schema.json

  - id: map_review_to_paragraphs
    placeholder: true
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: typography_reviews
        pattern: review/{lang}/typography/review.json
        schema: review.schema.json
      - family: critics_reviews
        pattern: review/{lang}/critics/review.json
        schema: review.schema.json
      - family: candidate_paragraph_maps
        pattern: final/{lang}/candidate_map.jsonl
        schema: candidate_map.schema.json
    outputs:
      - family: typography_paragraph_rows
        pattern: review/{lang}/normalized/typography_paragraph_rows.jsonl
        schema: paragraph_rows.schema.json
      - family: critics_paragraph_rows
        pattern: review/{lang}/normalized/critics_paragraph_rows.jsonl
        schema: paragraph_rows.schema.json

  - id: aggregate_paragraph_reviews
    placeholder: true
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: grammar_reviews
        pattern: review/grammar/review.json
        schema: review.schema.json
      - family: typography_paragraph_rows
        pattern: review/{lang}/normalized/typography_paragraph_rows.jsonl
        schema: paragraph_rows.schema.json
      - family: critics_paragraph_rows
        pattern: review/{lang}/normalized/critics_paragraph_rows.jsonl
        schema: paragraph_rows.schema.json
    outputs:
      - family: paragraph_scores
        pattern: state/{lang}/paragraph_scores.jsonl
        schema: paragraph_scores.schema.json
      - family: rework_queue
        pattern: state/{lang}/rework_queue.jsonl
        schema: rework_queue.schema.jsonl

  - id: final_assembly_and_publish_gate
    placeholder: true
    foreach: params.targets.languages
    key: lang
    mode: whole_run
    inputs:
      - family: pass2_translations
        pattern: pass2_pre/{lang}/paragraphs.jsonl
        schema: paragraphs.schema.json
      - family: paragraphs
        pattern: paragraphs.jsonl
        schema: paragraphs.schema.json
    outputs:
      - family: final_manuscripts
        pattern: final/{lang}/final.md
        schema: candidate.schema.json
      - family: final_paragraphs
        pattern: final/{lang}/final_pre/paragraphs.jsonl
        schema: paragraphs.schema.json
      - family: gate_reports
        pattern: gate/{lang}/gate_report.json
        schema: gate_report.schema.json
