pipeline_id: translate-pipeline
item_unit: paragraph
determinism_policy: strict
stages:
  - id: source_ingest
    mode: whole_run
    inputs: []
    outputs:
      - paragraphs.jsonl
      - manifest.json

  - id: translate_pass1
    mode: whole_run
    inputs:
      - paragraphs.jsonl
    outputs:
      - pass1_pre/paragraphs.jsonl

  - id: translate_pass2
    placeholder: true
    mode: whole_run
    inputs:
      - pass1_pre/paragraphs.jsonl
    outputs:
      - pass2_pre/paragraphs.jsonl

  - id: candidate_assembly
    placeholder: true
    mode: whole_run
    inputs:
      - pass2_pre/paragraphs.jsonl
    outputs:
      - final/candidate.md
      - final/candidate_map.jsonl

  - id: review_grammar
    placeholder: true
    mode: whole_run
    inputs:
      - pass2_pre/paragraphs.jsonl
    outputs:
      - review/grammar/review.json

  - id: review_typography
    placeholder: true
    mode: whole_run
    inputs:
      - final/candidate.md
    outputs:
      - review/typography/review.json

  - id: review_critics
    placeholder: true
    mode: whole_run
    inputs:
      - final/candidate.md
    outputs:
      - review/critics/review.json

  - id: map_review_to_paragraphs
    placeholder: true
    mode: whole_run
    inputs:
      - review/typography/review.json
      - review/critics/review.json
      - final/candidate_map.jsonl
    outputs:
      - review/normalized/typography_paragraph_rows.jsonl
      - review/normalized/critics_paragraph_rows.jsonl

  - id: aggregate_paragraph_reviews
    placeholder: true
    mode: whole_run
    inputs:
      - review/grammar/review.json
      - review/normalized/typography_paragraph_rows.jsonl
      - review/normalized/critics_paragraph_rows.jsonl
    outputs:
      - state/paragraph_scores.jsonl
      - state/rework_queue.jsonl

  - id: final_assembly_and_publish_gate
    placeholder: true
    mode: whole_run
    inputs:
      - pass2_pre/paragraphs.jsonl
      - paragraphs.jsonl
    outputs:
      - final/final.md
      - final/final_pre/paragraphs.jsonl
      - gate/gate_report.json
